// Generates the Dart bindings for the engine's Objective-C interface.
//
// Run `tool/generate_bindings.sh`, which first writes the header this reads.
import 'dart:io';

import 'package:ffigen/ffigen.dart';
import 'package:logging/logging.dart';

final _root = Platform.script.resolve('../');

void main() {
  Logger.root.level = Level.WARNING;
  Logger.root.onRecord.listen((r) => stderr.writeln('${r.level.name}: ${r.message}'));
  FfiGenerator(
    headers: Headers(
      entryPoints: [_root.resolve('ios/ovoz/Sources/ovoz_ffi/include/ovoz_objc_api.h')],
      include: (header) => header.path.endsWith('ovoz_objc_api.h'),
    ),
    objectiveC: ObjectiveC(
      interfaces: Interfaces.includeSet({'OvozItem', 'OvozPlayer', 'OvozSession'}),
      protocols: Protocols.includeSet({'OvozPlayerListener', 'OvozSessionListener'}),
    ),
    output: Output(
      dartFile: _root.resolve('lib/src/platform/darwin/ovoz_bindings.g.dart'),
      objectiveCFile: _root.resolve('ios/ovoz/Sources/ovoz_ffi/ovoz_bindings.g.m'),
      preamble: '// Generated by tool/generate_bindings.sh. Do not edit.',
    ),
  ).generate(logger: Logger.root);
}
