// Generated by Apple Swift version 6.4 effective-5.10 (swiftlang-6.4.0.34.1 clang-2100.3.34.1)
#ifndef OVOZ_SWIFT_H
#define OVOZ_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ovoz",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Warc-bridge-casts-disallowed-in-nonarc"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ovoz",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSData;
/// What Dart asks a player to play: a cheap descriptor, turned into an
/// <code>AVPlayerItem</code> only when it enters the player’s window (D-04, PL-07).
/// [itemId] is chosen by Dart and is new every time an item is handed over,
/// even for the same source, so events always say which instance they are
/// about (a looped item is a new instance each lap).
SWIFT_CLASS_NAMED("OvozItem")
@interface OvozItem : NSObject
@property (nonatomic, readonly) int64_t itemId;
/// <code>file:///…</code>, <code>asset:///<flutter asset key></code>, <code>http(s)://…</code>.
@property (nonatomic, readonly, copy) NSString * _Nonnull uri;
/// Declared container format (<code>mp3</code>, <code>m4a</code>, …). Required for encrypted
/// sources, which AVFoundation cannot sniff.
@property (nonatomic, copy) NSString * _Nullable format;
/// Clip bounds in milliseconds; <code>clipEndMs < 0</code> plays to the end.
@property (nonatomic) int64_t clipStartMs;
@property (nonatomic) int64_t clipEndMs;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable artist;
@property (nonatomic, copy) NSString * _Nullable album;
@property (nonatomic, copy) NSString * _Nullable artworkUri;
/// Length to show before the player has measured it; < 0 when unknown.
@property (nonatomic) int64_t durationHintMs;
- (nonnull instancetype)initWithItemId:(int64_t)itemId uri:(NSString * _Nonnull)uri OBJC_DESIGNATED_INITIALIZER;
/// Sent with every HTTP request for this item.
- (void)addHeader:(NSString * _Nonnull)name value:(NSString * _Nonnull)value;
/// Decrypts the source with AES-CTR. With [ivInHeader] the IV is read from
/// the first 16 bytes of the file and [iv] is ignored. [dataOffset] is where
/// the ciphertext starts.
- (void)setAesCtrWithKey:(NSData * _Nonnull)key iv:(NSData * _Nonnull)iv ivInHeader:(BOOL)ivInHeader dataOffset:(int64_t)dataOffset;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol OvozPlayerListener;
/// One playback stream (D-17: many may exist).
/// A mechanism, not a policy: it plays the item it is given, keeps the next
/// item Dart cued ready for a gapless transition, and reports what happens.
/// Which item comes next — order, shuffle, loop, what “previous” means — is
/// decided in Dart, once for every platform. The two-item window is all the
/// native side needs to advance without waiting for Dart (D-04).
/// Every method is called on the main thread: Dart runs there (merged
/// UI/platform threads, IO-01), and AVFoundation state is only touched there.
SWIFT_CLASS_NAMED("OvozPlayer")
@interface OvozPlayer : NSObject
- (nonnull instancetype)initWithListener:(id <OvozPlayerListener> _Nonnull)listener OBJC_DESIGNATED_INITIALIZER;
/// Makes [item] current, starting at [positionMs] within it (within its
/// clip), and drops any cued item. Keeps playing if playback was wanted.
/// Nil empties the player.
- (void)setItem:(OvozItem * _Nullable)item positionMs:(int64_t)positionMs;
/// Cues [item] to follow the current one without a gap; nil cues nothing,
/// so the current item ends the stream (or pauses, see [pauseAtItemEnd]).
- (void)setNextItem:(OvozItem * _Nullable)item;
/// When true, the end of an item pauses playback instead of continuing; a
/// cued item becomes current, paused at its start (“stop after this
/// chapter”).
@property (nonatomic) BOOL pauseAtItemEnd;
- (void)play;
- (void)pause;
/// Releases the items and their decoders. Dart keeps the queue and the
/// position, and sets the item again to resume.
- (void)stop;
- (void)seekToMs:(int64_t)positionMs;
- (void)setSpeed:(double)value;
- (void)setVolume:(double)value;
/// 0: speech quality (time domain), 1: music quality (spectral), 2: no pitch
/// correction (varispeed).
- (void)setPitchCorrection:(NSInteger)mode;
@property (nonatomic, readonly) int64_t positionMs;
@property (nonatomic, readonly) int64_t bufferedPositionMs;
/// -1 while unknown, and for live streams.
@property (nonatomic, readonly) int64_t durationMs;
/// -1 when nothing is loaded.
@property (nonatomic, readonly) int64_t currentItemId;
@property (nonatomic, readonly) NSInteger processingState;
@property (nonatomic, readonly) BOOL isPlaying;
/// Whether the device has a network, as last reported; true until the
/// first report.
@property (nonatomic, readonly) BOOL isNetworkAvailable;
/// Makes this player the one the lock screen, Control Center, headsets and
/// cars control (BG-02: at most one player at a time; this takes over from
/// any other). [commands] is a bit set of [OvozRemoteCommand] raw values.
- (void)enableMediaControls:(NSInteger)commands skipForwardMs:(int64_t)skipForwardMs skipBackwardMs:(int64_t)skipBackwardMs;
/// Takes this player off the lock screen (if it is there).
- (void)disableMediaControls;
/// “3 of 12” on the lock screen.
- (void)setQueuePosition:(NSInteger)index count:(NSInteger)count;
/// Stops playback and releases everything. The player cannot be used again.
- (void)dispose;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Native events for one player, implemented in Dart (EVT-01).
/// Calls are asynchronous: they are posted to the Dart isolate and may come
/// from any thread. Values that change continuously (position, buffered
/// position) are not pushed; Dart reads them synchronously (EVT-03).
SWIFT_PROTOCOL_NAMED("OvozPlayerListener")
@protocol OvozPlayerListener <NSObject>
/// [state] is an [OvozProcessingState]; [playing] is whether playback is
/// wanted, which stays true while loading or buffering.
- (void)onStateChanged:(NSInteger)state playing:(BOOL)playing;
/// Item [itemId] became current: loaded by <code>setItem</code>, or reached by
/// advancing into the cued next item.
- (void)onItemStarted:(int64_t)itemId;
/// Item [itemId] played to its end. Never sent for an item that was
/// replaced, skipped or stopped.
- (void)onItemEnded:(int64_t)itemId;
- (void)onDurationChanged:(int64_t)itemId durationMs:(int64_t)durationMs;
/// [code] is an [OvozErrorCode].
- (void)onError:(int64_t)itemId code:(NSInteger)code message:(NSString * _Nonnull)message;
/// A lock-screen, headset or car command, for the player that owns the
/// media controls. [command] is an [OvozRemoteCommand]; [value] carries the
/// position or interval in milliseconds, or the rate.
- (void)onRemoteCommand:(NSInteger)command value:(double)value;
/// The network came back, went away, or moved to another interface (Wi-Fi
/// to cellular): [available] is whether there is one now.
- (void)onNetworkChanged:(BOOL)available;
@end

/// Processing states; the raw values are shared with Dart’s <code>ProcessingState</code>.
typedef SWIFT_ENUM_NAMED(NSInteger, OvozProcessingState, "OvozProcessingState", closed) {
  OvozProcessingStateIdle = 0,
  OvozProcessingStateLoading = 1,
  OvozProcessingStateBuffering = 2,
  OvozProcessingStateReady = 3,
  OvozProcessingStateCompleted = 4,
};

/// Commands the lock screen, Control Center, headsets and cars can send. The
/// raw values are shared with Dart’s <code>MediaCommand</code>; as bit positions they
/// also form the set passed to <code>enableMediaControls</code>.
typedef SWIFT_ENUM_NAMED(NSInteger, OvozRemoteCommand, "OvozRemoteCommand", closed) {
  OvozRemoteCommandPlay = 0,
  OvozRemoteCommandPause = 1,
  OvozRemoteCommandTogglePlayPause = 2,
  OvozRemoteCommandStop = 3,
  OvozRemoteCommandNext = 4,
  OvozRemoteCommandPrevious = 5,
  OvozRemoteCommandSeek = 6,
  OvozRemoteCommandSkipForward = 7,
  OvozRemoteCommandSkipBackward = 8,
  OvozRemoteCommandChangeRate = 9,
};

@protocol OvozSessionListener;
/// The app-wide audio session, configured from Dart (D-14).
/// Categories, modes and options travel as their Dart enum indices and option
/// bits, mapped here, so Dart never needs AVFoundation’s string constants.
SWIFT_CLASS_NAMED("OvozSession")
@interface OvozSession : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) OvozSession * _Nonnull shared;)
+ (OvozSession * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)setListener:(id <OvozSessionListener> _Nullable)listener;
/// Returns nil on success, or why the configuration was refused.
- (NSString * _Nullable)configureWithManaged:(BOOL)managed category:(NSInteger)category mode:(NSInteger)mode options:(NSInteger)options routeSharingPolicy:(NSInteger)routeSharingPolicy interruptionPolicy:(NSInteger)interruptionPolicy pauseOnBecomingNoisy:(BOOL)pauseOnBecomingNoisy deactivateWhenIdle:(BOOL)deactivateWhenIdle SWIFT_WARN_UNUSED_RESULT;
/// Returns nil on success, or the reason it failed (for example another
/// app holding a non-mixable session).
- (NSString * _Nullable)setActive:(BOOL)active SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL hasAudioBackgroundMode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Session events, implemented in Dart.
SWIFT_PROTOCOL_NAMED("OvozSessionListener")
@protocol OvozSessionListener <NSObject>
- (void)onInterruption:(BOOL)began shouldResume:(BOOL)shouldResume;
/// Headphones were unplugged: audio is about to come out of the speaker.
- (void)onBecomingNoisy;
/// [reason] is an <code>AVAudioSession.RouteChangeReason</code> raw value.
- (void)onRouteChanged:(NSInteger)reason;
/// The system’s media services restarted; players may need to reload.
- (void)onMediaServicesReset;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
